#pragma once
//寻找，校验ISO
#define WM_MYMSG_FindISOEnd (WM_USER + 100)
//GHOST备份
#define WM_MYMSG_GHOST_BACKUP_END (WM_USER + 101)
//GHOST恢复
#define WM_MYMSG_GHOST_RESTORE_END	(WM_USER + 102)
//ImageEx备份
#define WM_MYMSG_IMAGEX_BACKUP_END (WM_USER +103)